-- Script SQL untuk menambahkan data kode arsip lengkap
-- Tanggal: 2024

-- KODE KEUNGAN (KU)
INSERT INTO `tb_kode_arsip` (`kode`, `nama`, `createDate`) VALUES
('KU0101', 'KU0101 – Penyusunan Target & Pagu Indikatif PNBP (arsip penyusunan target dan pagu PNBP)', NOW()),
('KU0102', 'KU0102 – Penyusunan RBA BLU (arsip penyusunan Rencana Bisnis Anggaran BLU)', NOW()),
('KU0201', 'KU0201 – Belanja Pegawai (gaji, tunjangan, honorarium, uang makan, lembur)', NOW()),
('KU0202', 'KU0202 – Belanja Barang & Jasa (ATK, konsumsi, listrik, air, telepon, penggandaan, inventaris kecil)', NOW()),
('KU0203', 'KU0203 – Belanja Pemeliharaan (gedung, rumah dinas, kendaraan, inventaris, peralatan)', NOW()),
('KU0204', 'KU0204 – Belanja Sewa (sewa gedung, sewa peralatan dan mesin)', NOW()),
('KU0205', 'KU0205 – Belanja Perjalanan (SPD, perjalanan dinas, meeting dalam/luar kota, luar negeri)', NOW()),
('KU0206', 'KU0206 – Belanja Bantuan Pemerintah (bantuan barang/uang ke masyarakat/pemerintah daerah)', NOW()),
('KU0207', 'KU0207 – Belanja Modal Tanah (pengadaan, pembebasan, sertifikat, pematangan tanah)', NOW()),
('KU0208', 'KU0208 – Belanja Modal Peralatan & Mesin (pengadaan inventaris berumur >12 bulan)', NOW()),
('KU0209', 'KU0209 – Belanja Modal Gedung & Bangunan (pembangunan, perencanaan, pengawasan hingga siap pakai)', NOW()),
('KU0210', 'KU0210 – Belanja Modal Jalan, Irigasi & Jaringan (pembangunan, peningkatan, perawatan jaringan infrastruktur)', NOW()),
('KU0211', 'KU0211 – Belanja Modal Aset Lainnya (software, studi, aset tak berwujud lainnya)', NOW()),
('KU0212', 'KU0212 – Belanja Lainnya (bencana alam, tanggap darurat, dll.)', NOW()),
('KU0301', 'KU0301 – Dokumen Pengeluaran Anggaran (SPP, SPP-GU, SPP-LS, SPP-TUP, SPBy, Surat Kuasa, SPM, SP2D)', NOW()),
('KU0401', 'KU0401 – PNBP (transaksi PNBP online, tarif, MP pencairan PNBP)', NOW()),
('KU0402', 'KU0402 – Pengembalian Belanja (pengembalian TA berjalan & lintas TA)', NOW()),
('KU0403', 'KU0403 – Tuntutan Ganti Rugi (TGR) (SKTJM, penagihan, keterangan lunas)', NOW()),
('KU0404', 'KU0404 – Tuntutan Perbendaharaan (tuntutan terhadap bendahara, SKTJM)', NOW()),
('KU0405', 'KU0405 – Perhitungan Ex-Officio (perhitungan saat pejabat tidak bisa mempertanggungjawabkan)', NOW()),
('KU0406', 'KU0406 – Pembukaan Rekening Bendahara (permohonan & laporan rekening bendahara)', NOW()),
('KU0407', 'KU0407 – Berita Acara Pemeriksaan Kas (BAPK kas rutin)', NOW()),
('KU0408', 'KU0408 – Verifikasi Anggaran (pengujian RKA, bukti pengeluaran, administrasi)', NOW()),
('KU0409', 'KU0409 – Nota Verifikasi Pertanggungjawaban (memo penyesuaian, pengembalian SPP/SPM)', NOW()),
('KU0410', 'KU0410 – Pembukuan Anggaran (BKU, BKP, kartu realisasi & monitoring DIPA)', NOW()),
('KU0411', 'KU0411 – Pendampingan Perbendaharaan (bimbingan anggaran, pencairan, laporan, tindak lanjut LHP)', NOW()),
('KU0412', 'KU0412 – Pembinaan Perbendaharaan (sosialisasi aturan & kebijakan keuangan)', NOW()),
('KU0501', 'KU0501 – LPJ Bendahara (BAPK, rekonsiliasi, saldo rekening, koran)', NOW()),
('KU0502', 'KU0502 – Pelaporan PNBP (umum, fungsional, BLU)', NOW()),
('KU0503', 'KU0503 – Pelaporan Keuangan (SAI) (LRA, Neraca, CALK, LO, LPE)', NOW()),
('KU0504', 'KU0504 – Pelaporan Pajak (pelaporan pajak bendahara ke KPP)', NOW()),
('KU0505', 'KU0505 – Pelaporan Piutang Negara (TGR, sewa rumah negara gol III)', NOW()),
('KU0601', 'KU0601 – Evaluasi Laporan Keuangan (eselon I, satker, kementerian)', NOW()),
('KU0602', 'KU0602 – Evaluasi Kinerja Pelaksanaan Anggaran (penyerapan, revisi, retur SPM/SP2D, data kontrak)', NOW()),
('KU0603', 'KU0603 – Evaluasi Pejabat Perbendaharaan (administrasi & teknis pejabat)', NOW()),
('KU0604', 'KU0604 – Evaluasi Kinerja BLU (performansi BLU)', NOW()),
('KU0701', 'KU0701 – KP4 (surat keterangan penerimaan tunjangan keluarga)', NOW()),
('KU0702', 'KU0702 – Keterangan Penghasilan (slip/keterangan penghasilan pegawai)', NOW()),
('KU0703', 'KU0703 – SKPP (surat pemberhentian pembayaran gaji)', NOW()),
('KU0704', 'KU0704 – Penyampaian SPT Pajak (laporan SPT tahunan/manual/e-filing)', NOW()),

-- KODE KEPEGAWAIAN (KP)
('KP0101', 'KP0101 – Analisa Jabatan (uraian tugas, evaluasi jabatan, spesifikasi jabatan, DUPAK/DUK)', NOW()),
('KP0102', 'KP0102 – Analisa Beban Kerja (pengukuran beban kerja, pemetaan kebutuhan pegawai)', NOW()),
('KP0103', 'KP0103 – Formasi Kepegawaian (rencana formasi, pengadaan CPNS, bezetting pegawai)', NOW()),
('KP0201', 'KP0201 – Penerimaan Pegawai (pengumuman, lamaran, seleksi, hasil seleksi)', NOW()),
('KP0202', 'KP0202 – Pengangkatan CPNS/PNS (pemberkasan, NIP, SK CPNS/PNS)', NOW()),
('KP0203', 'KP0203 – Penempatan CPNS/PNS (penugasan, surat penempatan)', NOW()),
('KP0204', 'KP0204 – Penerimaan & Penempatan PPPK/Non-PNS (seleksi dan penempatan PPPK/Non-PNS)', NOW()),
('KP0301', 'KP0301 – Ujian Penyesuaian Ijazah (berkas ujian penyesuaian ijazah)', NOW()),
('KP0302', 'KP0302 – Ujian Dinas (arsip ujian dinas)', NOW()),
('KP0303', 'KP0303 – Ujian Kompetensi/Assessment (tes kompetensi untuk kenaikan pangkat/jabatan)', NOW()),
('KP0401', 'KP0401 – Kenaikan & Penyesuaian Pangkat/Golongan (KP, penyesuaian pangkat)', NOW()),
('KP0402', 'KP0402 – Rotasi Kerja (perpindahan antar-unit dalam instansi)', NOW()),
('KP0403', 'KP0403 – Alih Tugas (mutasi antar-instansi, diperbantukan)', NOW()),
('KP0404', 'KP0404 – Penempatan Kembali (setelah CLTN, tugas belajar, diperbantukan)', NOW()),
('KP0501', 'KP0501 – Pengangkatan Jabatan Struktural (pengangkatan, pelantikan)', NOW()),
('KP0502', 'KP0502 – Pemberhentian Jabatan Struktural (SK pemberhentian dari jabatan)', NOW()),
('KP0601', 'KP0601 – Data Pegawai (DR H, Akta, KTP, KK, surat nikah/cerai, dll.)', NOW()),
('KP0602', 'KP0602 – Absensi Pegawai (rekap kehadiran)', NOW()),
('KP0603', 'KP0603 – Kartu-Kartu Kepegawaian (ID Card, Karpeg, Karsu/Karis, Taspen, BPJS)', NOW()),
('KP0604', 'KP0604 – Tanda Jasa (penghargaan masa kerja, pegawai teladan)', NOW()),
('KP0605', 'KP0605 – Penggajian (kenaikan gaji berkala, gaji istimewa)', NOW()),
('KP0606', 'KP0606 – Penyesuaian Masa Kerja (penyesuaian MKG)', NOW()),
('KP0607', 'KP0607 – Penyesuaian Kelas Jabatan (penyesuaian kelas jabatan akibat perubahan)', NOW()),
('KP0701', 'KP0701 – Cuti Pegawai (cuti tahunan, cuti besar, cuti melahirkan, CLTN)', NOW()),
('KP0801', 'KP0801 – Penilaian Prestasi Kerja (SKP) (SKP, penilaian kinerja)', NOW()),
('KP0802', 'KP0802 – Pembinaan Karakter Pegawai (pembinaan jasmani & rohani)', NOW()),
('KP0803', 'KP0803 – Hukuman Disiplin (tegur lisan/tertulis, penurunan pangkat)', NOW()),
('KP0804', 'KP0804 – Penyelesaian Sengketa Pegawai (rekam perselisihan, perceraian)', NOW()),
('KP0901', 'KP0901 – Pengembangan Karir (pemetaan, pembinaan, pola karir)', NOW()),
('KP0902', 'KP0902 – Pelatihan Keterampilan/Keahlian (pola keterampilan dan keahlian)', NOW()),
('KP0903', 'KP0903 – Tugas Belajar/Izin Belajar (permohonan, penetapan tugas belajar/izin belajar)', NOW()),
('KP0904', 'KP0904 – Sertifikasi Profesi (arsip sertifikasi profesi ASN)', NOW()),
('KP1001', 'KP1001 – Pengangkatan JFT (usulan & SK pengangkatan)', NOW()),
('KP1002', 'KP1002 – Kenaikan Jenjang JFT (kenaikan pangkat/jenjang JF)', NOW()),
('KP1003', 'KP1003 – Pemindahan JFT (mutasi antar-jabatan fungsional)', NOW()),
('KP1004', 'KP1004 – Pembebasan Sementara JFT (pembebasan sementara)', NOW()),
('KP1005', 'KP1005 – Pemberhentian JFT (SK pemberhentian JF)', NOW()),
('KP1101', 'KP1101 – Pemberhentian Dengan Hormat (pengajuan & SK pemberhentian DH)', NOW()),
('KP1102', 'KP1102 – Pemberhentian Tidak Dengan Hormat (SK PTDH, proses pemeriksaan)', NOW()),
('KP1201', 'KP1201 – Pensiun Pegawai (berkas pensiun, SK, hak pensiun, Taspen)', NOW()),

-- KODE PENGELOLAAN SARANA (PS)
('PS01', 'PS01 – Pengadaan', NOW()),
('PS0101', 'PS0101 – Pengadaan Aset Lancar', NOW()),
('PS0102', 'PS0102 – Pengadaan Aset Tetap', NOW()),
('PS0103', 'PS0103 – Pengadaan Aset Lainnya', NOW()),
('PS02', 'PS02 – Penggunaan', NOW()),
('PS0201', 'PS0201 – Penetapan Status Penggunaan', NOW()),
('PS0202', 'PS0202 – Penggunaan Sementara / Pengalihan Status / Operasional oleh Pihak Lain', NOW()),
('PS03', 'PS03 – Pemanfaatan & Pemeliharaan', NOW()),
('PS0301', 'PS0301 – Pemanfaatan BMN (sewa, KSP, BGS/BSG, KSP Infrastruktur, pinjam pakai)', NOW()),
('PS0302', 'PS0302 – Pemeliharaan BMN', NOW()),
('PS0303', 'PS0303 – Pemeriksaan BMN', NOW()),
('PS04', 'PS04 – Pemindahtanganan', NOW()),
('PS0401', 'PS0401 – Penjualan BMN', NOW()),
('PS0402', 'PS0402 – Tukar Menukar BMN', NOW()),
('PS0403', 'PS0403 – Hibah BMN', NOW()),
('PS0404', 'PS0404 – Penyertaan Modal Pemerintah Pusat', NOW()),
('PS05', 'PS05 – Penghapusan, Pemusnahan, Pengawasan & Pengendalian', NOW()),
('PS0501', 'PS0501 – Penghapusan & Pemusnahan BMN', NOW()),
('PS0502', 'PS0502 – Pengawasan & Pengendalian BMN', NOW()),
('PS06', 'PS06 – Penatausahaan', NOW()),
('PS0601', 'PS0601 – Pembukuan BMN (SIMAK-BMN)', NOW()),
('PS0602', 'PS0602 – Inventarisasi & Revaluasi BMN', NOW()),
('PS0603', 'PS0603 – Pelaporan BMN', NOW()),

-- KODE ORGANISASI (OR)
('OR01', 'OR01 – Organisasi', NOW()),
('OR0101', 'OR0101 – Struktur Organisasi', NOW()),
('OR0102', 'OR0102 – Tata Kerja & Uraian Tugas Pokok', NOW()),
('OR02', 'OR02 – Ketatalaksanaan', NOW()),
('OR0201', 'OR0201 – Tata Laksana (Proses Bisnis)', NOW()),
('OR0202', 'OR0202 – Mekanisme Kerja (SOP, SMM, dll.)', NOW()),
('OR0203', 'OR0203 – Reformasi Birokrasi', NOW()),
('OR0204', 'OR0204 – Budaya Organisasi', NOW()),
('OR03', 'OR03 – Organisasi Non Kedinasan', NOW()),
('OR0301', 'OR0301 – KORPRI', NOW()),
('OR0302', 'OR0302 – Dharma Wanita', NOW()),
('OR0303', 'OR0303 – Koperasi', NOW()),
('OR0304', 'OR0304 – Kerukunan Pensiun PU (KPPU)', NOW()),

-- KODE PENGADAAN BARANG (PB)
('PB01', 'PB01 – Pengadaan Barang', NOW()),
('PB0101', 'PB0101 – Melalui Pelelangan Umum', NOW()),
('PB0102', 'PB0102 – Melalui Pelelangan Terbatas', NOW()),
('PB0103', 'PB0103 – Melalui Pelelangan Sederhana', NOW()),
('PB0104', 'PB0104 – Melalui Penunjukan Langsung', NOW()),
('PB0105', 'PB0105 – Melalui Pengadaan Langsung', NOW()),
('PB0106', 'PB0106 – Melalui Kontes', NOW()),
('PB02', 'PB02 – Pengadaan Pekerjaan Konstruksi', NOW()),
('PB0201', 'PB0201 – Melalui Pelelangan Umum', NOW()),
('PB0202', 'PB0202 – Melalui Pelelangan Terbatas', NOW()),
('PB0203', 'PB0203 – Melalui Pemilihan Langsung', NOW()),
('PB0204', 'PB0204 – Melalui Penunjukan Langsung', NOW()),
('PB0205', 'PB0205 – Melalui Pengadaan Langsung', NOW()),
('PB03', 'PB03 – Pengadaan Jasa Konsultasi', NOW()),
('PB0301', 'PB0301 – Melalui Seleksi Umum', NOW()),
('PB0302', 'PB0302 – Melalui Seleksi Sederhana', NOW()),
('PB0303', 'PB0303 – Melalui Penunjukan Langsung', NOW()),
('PB0304', 'PB0304 – Melalui Pengadaan Langsung', NOW()),
('PB0305', 'PB0305 – Melalui Sayembara', NOW()),
('PB04', 'PB04 – Pengadaan Jasa Lainnya', NOW()),
('PB0401', 'PB0401 – Melalui Pelelangan Umum', NOW()),
('PB0402', 'PB0402 – Melalui Pelelangan Sederhana', NOW()),
('PB0403', 'PB0403 – Melalui Penunjukan Langsung', NOW()),
('PB0404', 'PB0404 – Melalui Pengadaan Langsung', NOW()),
('PB0405', 'PB0405 – Melalui Sayembara', NOW()),

-- KODE PERENCANAAN (PR)
('PR0101', 'PR0101 – Penyusunan Rencana & Program Unit Kerja (rencana & program tiap unit organisasi)', NOW()),
('PR0102', 'PR0102 – Strategi & Dokumen Perencanaan Pembangunan (RPJP, RPJM, Renstra, RKT, Renja K/L, Musrenbangnas, rencana daerah khusus)', NOW()),
('PR0103', 'PR0103 – Penetapan Kinerja Tahunan (penyusunan & penetapan kinerja tahunan)', NOW()),
('PR0201', 'PR0201 – Penyusunan Penganggaran (KAK, RAB, RKA-KL, DIPA, POK) (termasuk usulan, revisi, pagu indikatif, pagu anggaran, alokasi)', NOW()),
('PR0202', 'PR0202 – Sistem Penganggaran (persiapan bahan, koordinasi, pengelolaan sistem penganggaran)', NOW()),
('PR0203', 'PR0203 – Analisis Data Penganggaran (analisis, koordinasi, fasilitasi pengesahan dokumen anggaran)', NOW()),
('PR0204', 'PR0204 – Fasilitasi Pendanaan Daerah (DAK) (analisis, penyusunan, pengelolaan, evaluasi, pelaporan DAK)', NOW()),
('PR0301', 'PR0301 – Pemantauan Kinerja & Anggaran (pemantauan, pengelolaan data kinerja & anggaran)', NOW()),
('PR0302', 'PR0302 – Evaluasi Kinerja & Pelaksanaan Anggaran (siapkan bahan evaluasi)', NOW()),
('PR0303', 'PR0303 – Pelaporan Realisasi (Bulanan/Triwulan/Tahunan) (termasuk laporan program prioritas, strategis, instruksi Menteri/Presiden)', NOW()),
('PR0304', 'PR0304 – Laporan LAKIP (pengolahan LAKIP)', NOW()),

-- KODE PENGAWASAN (PW)
('PW0101', 'PW0101 – Pemeriksaan Administrasi Umum (mencakup identitas, tugas pokok, organisasi, kepegawaian, BMN, pengadaan, rencana → laporan)', NOW()),
('PW0102', 'PW0102 – Pemeriksaan Keuangan (kas bendahara, bukti penerimaan/pengeluaran, laporan keuangan, LRA, Neraca, CALK, output DIPA)', NOW()),
('PW0103', 'PW0103 – Pemeriksaan Kinerja (perencanaan → pelelangan → kontrak → progres → pengendalian → kualitas → manfaat)', NOW()),
('PW0104', 'PW0104 – Pemeriksaan Khusus (TPK, pelanggaran disiplin, KKN, pengadaan, tindak pidana umum, kasus berindikasi masalah)', NOW()),
('PW0105', 'PW0105 – Reviu Keuangan dan Kegiatan (reviu laporan keuangan semesteran & tahunan)', NOW()),
('PW0201', 'PW0201 – Laporan Hasil Audit (LHA) APIP (ikhtisar LHA ke KemenPAN-RB, BPKP, UKP4, tanggapan BPK RI)', NOW()),
('PW0202', 'PW0202 – Tindak Lanjut Hasil Audit (tindak lanjut LHA Itjen, BPK, dan LHA lainnya)', NOW()),
('PW0203', 'PW0203 – Tuntutan Ganti Rugi (TGR/TP) (pemantauan kerugian negara → rencana → penyelesaian)', NOW()),
('PW0204', 'PW0204 – Evaluasi Kegiatan/Kinerja (evaluasi LAKIP, RB, dan evaluasi lainnya)', NOW()),
('PW0205', 'PW0205 – Penerapan Early Warning System (EWS) (fasilitasi dan pemantauan pengelolaan keuangan → laporan)', NOW()),
('PW0301', 'PW0301 – Pengaduan Internal (pelaporan, penanganan, penyelesaian)', NOW()),
('PW0302', 'PW0302 – Pengaduan Eksternal (pelaporan, penanganan, penyelesaian)', NOW()),
('PW0401', 'PW0401 – Pendampingan Pengawasan (pendampingan EPPD, bencana, BMN, dll)', NOW()),
('PW0402', 'PW0402 – Bimbingan dan Konsultasi Pengawasan (rencana → pelaksanaan → laporan)', NOW()),
('PW0403', 'PW0403 – Pengelolaan & Pemaparan Hasil Pengawasan (pengelolaan data hasil pengawasan & pemaparan)', NOW()),
('PW0404', 'PW0404 – Sosialisasi Pengawasan (sosialisasi, forum komunikasi APIP, dll)', NOW()),

-- KODE UMUM (UM)
('UM0101', 'UM0101 – Peringatan Hari Kemerdekaan/Hari Besar Nasional/Hari Bhakti PUPR', NOW()),
('UM0102', 'UM0102 – Rapat/Raker/Rakor/Rapat Teknis/Konsultasi Regional', NOW()),
('UM0103', 'UM0103 – Administrasi Perjalanan Dinas', NOW()),
('UM0104', 'UM0104 – Penghargaan/Kenang-kenangan/Hadiah/Belasungkawa', NOW()),
('UM0105', 'UM0105 – Pengaturan Jam Kerja', NOW()),
('UM0201', 'UM0201 – Penciptaan Tata Naskah Dinas (Surat Masuk/Keluar, Disposisi)', NOW()),
('UM0202', 'UM0202 – Pengelolaan Arsip Dinamis (Pemberkasan, Penataan, Penyimpanan, Alih Media)', NOW()),
('UM0203', 'UM0203 – Penyusutan Arsip (Pemindahan, Penyerahan, Pemusnahan)', NOW()),
('UM0204', 'UM0204 – Pembinaan Kearsipan (Pedoman, Bimtek, Sosialisasi, Lomba Arsip)', NOW()),
('UM0205', 'UM0205 – Fasilitasi Arsip Statis (Inventarisasi, Ikhtisar, Penyerahan ke ANRI)', NOW()),
('UM0301', 'UM0301 – Penggunaan Sarana/Prasarana Kantor (Gedung, Aula, Ruang Rapat, KDO, Rumah Dinas)', NOW()),
('UM0302', 'UM0302 – Pemeliharaan Sarana/Prasarana Kantor', NOW()),
('UM0303', 'UM0303 – Jaringan Listrik, Air, Telepon (Pemasangan, Perbaikan, Pemeliharaan)', NOW()),
('UM0401', 'UM0401 – Pengamanan dan Pengawalan Gedung/Proyek/Rumah Jabatan', NOW()),
('UM0402', 'UM0402 – Izin Keluar-Masuk BMN', NOW()),
('UM0403', 'UM0403 – Kehilangan BMN/Barang di Area Kerja', NOW()),
('UM0404', 'UM0404 – Kerusakan BMN/Barang (Termasuk Bencana/Kebakaran)', NOW()),
('UM0405', 'UM0405 – Kecelakaan di Area Kantor/Proyek/Rumah Jabatan', NOW()),
('UM0406', 'UM0406 – Penertiban Perparkiran Pegawai/Pejabat/Tamu', NOW()),
('UM0407', 'UM0407 – Seragam/Pakaian Dinas (Ketentuan, Pembuatan, Pembagian)', NOW()),
('UM0501', 'UM0501 – Pelayanan Poliklinik Pegawai', NOW()),
('UM0502', 'UM0502 – Penyelenggaraan Perpustakaan', NOW()),
('UM0503', 'UM0503 – Penyelenggaraan Tempat Penitipan Anak', NOW()),
('UM0504', 'UM0504 – Penyelenggaraan Rumah Pintar', NOW()),
('UM0505', 'UM0505 – Administrasi/Penyelenggaraan Koperasi', NOW()),
('UM0601', 'UM0601 – Upacara/Acara Kedinasan (Pelantikan, Sertijab, Hari Besar)', NOW()),
('UM0602', 'UM0602 – Kunjungan Dinas Dalam/Luar Negeri', NOW()),
('UM0603', 'UM0603 – Agenda Pimpinan (Perencanaan, Penjadwalan, Pelaksanaan)', NOW()),
('UM0701', 'UM0701 – Kegiatan Kerohanian (Rutin/Insidental)', NOW()),
('UM0702', 'UM0702 – Kegiatan Olahraga', NOW()),
('UM0703', 'UM0703 – Kegiatan Kesenian', NOW()),
('UM0704', 'UM0704 – Pengumpulan/Penyaluran Sumbangan', NOW());


